<?php

use Faker\Generator as Faker;

$factory->define(App\Listing::class, function (Faker $faker) {
    return [
        'acreage' => $faker->numberBetween(1, 90),
        'area' => '23 x 23',
        'baths' => $faker->randomDigit,
        'baths_full' => $faker->randomDigit,
        'baths_half' => $faker->randomDigit,
        'bedrooms' => $faker->randomDigit,
        'cib_ceiling_height' => $faker->randomDigit,
        'cib_front_footage' => $faker->randomDigit,
        'city' => $faker->city,
        'co_la_code' => 'FSF23432',
        'co_lo_code' => 'FSF23432',
        'date_modified' => $faker->date,
        'directions' => $faker->sentence,
        'ftr_constrc' => $faker->sentence,
        'ftr_energy' => $faker->sentence,
        'ftr_exterior' => $faker->sentence,
        'ftr_forklift' => $faker->sentence,
        'ftr_hoaincl' => $faker->sentence,
        'ftr_interior' => $faker->sentence,
        'ftr_lotaccess' => $faker->sentence,
        'ftr_lotdesc' => $faker->sentence,
        'ftr_ownership' => $faker->sentence,
        'ftr_parking' => $faker->sentence,
        'ftr_projfacilities' => $faker->sentence,
        'ftr_sitedesc' => $faker->sentence,
        'ftr_transportation' => $faker->sentence,
        'ftr_utilities' => $faker->sentence,
        'ftr_waterfront' => $faker->sentence,
        'ftr_waterview' => $faker->sentence,
        'ftr_zoning' => $faker->sentence,
        'full_address' => $faker->streetName,
        'la_code' => 'FSDF2349',
        'legals' => $faker->sentence,
        'legal_block' => $faker->sentence,
        'legal_lot' => $faker->sentence,
        'legal_unit' => $faker->sentence,
        'list_date' => $faker->date,
        'list_price' => $faker->numberBetween(10000, 900000),
        'lot_dimensions' => $faker->sentence,
        'lo_code' => 'FSDF2349',
        'mls_acct' => $faker->randomNumber(5, true),
        'num_units' => $faker->randomDigit,
        'occupancy_yn' => $faker->randomElement(['y', 'n']),
        'parcel_id' => $faker->randomNumber,
        'parking_spaces' => $faker->randomDigit,
        'parking_type' => $faker->word,
        'photo_count' => $faker->randomDigit,
        'photo_date_modified' => $faker->date,
        'proj_name' => $faker->word,
        'prop_type' => $faker->word,
        'public_show_address' => $faker->boolean(),
        'remarks' => $faker->paragraph,
        'res_hoa_fee' => $faker->word,
        'res_hoa_term' => $faker->word,
        'sa_code' => $faker->word,
        'sold_date' => $faker->date,
        'sold_price' => $faker->numberBetween(100000, 100000000),
        'so_code' => $faker->word,
        'so_name' => $faker->word,
        'sqft_total' => $faker->numberBetween(100000, 100000000),
        'state' => $faker->state,
        'status' => $faker->word,
        'stories' => $faker->randomDigit,
        'street_name' => $faker->colorName,
        'street_num' => $faker->randomDigit,
        'subdivision' => $faker->word,
        'sub_area' => $faker->word,
        'tot_heat_sqft' => $faker->numberBetween(1000, 5000),
        'unit_num' => $faker->randomDigit,
        'wf_feet' => $faker->randomDigit,
        'year_built' => $faker->year,
        'zip' => $faker->randomNumber(5, true),
    ];
});
